#SnapshotCauses
SnapshotCauses <- list(
  USER_INPUT = 0,
  DRONE_REACH_WAYPOINT = 1,
  INCIDENT_STARTED = 2,
  INCIDENT_ENDED = 3,
  TARGET_DETECTED = 4,
  DRONE_DESTROYED = 5,
  ACTION_STARTED = 6,
  ACTION_ENDED = 7,
  CONTROL_MODE_CHANGED = 8,
  INSTRUCTION_SENT = 9,
  INSTRUCTION_COMPLETED = 10
)